### ISSUE TITLE
Marker のフォーカスが移ったときの挙動

### ISSUE THREAD

**Issue by tanacchi** [kyutech-programming-club/ena_sirube#2]
ピン選択時、表示されるウィンドウをウィンドウ以外を触るか、別のピンを選択すると消える仕様について

**Comment by tanacchi** [comment]
addMarkers 関数の以下のイベントいずれか（あるいは両方）を追加したらいけそう

**Comment by tanacchi** [comment]
```javascript
google.maps.event.addListener(this.markers[i], 'dblclick', function () {
  ...
}
```
の下に以下を追加

### 候補1
```javascript
 google.maps.event.addListener(this.markers[i], 'cursor_changed', function () {
        infoWindow.close();
 });
```

### 候補2
```javascript
 google.maps.event.addListener(this.markers[i], 'mouseout', function () {
        infoWindow.close();
 });
```

**Comment by rkdora** [comment]
候補1, 候補2,それぞれ＆両方の３通り試したけど、挙動に変わりなかった

**Comment by rkdora** [comment]
あと、ついでにいままでdblclickだったところをclickに変更した。

**Comment by tanacchi** [comment]
まちがえました

`mouseout`やら書いてたところを
`zindex_changed`に変えて！！！

**Comment by rkdora** [comment]
うんにゃ、かわらず。
addListener(this.markers[i],あたりが違う気がする。ちなみに、this→selfでもいっしょやった

**Comment by tanacchi** [comment]
あ，そうかも

`this.markers[i]` じゃなくて `infoWindow` かも

**Comment by rkdora** [comment]
なる。

```
      google.maps.event.addListener(self.map, 'dragend', function () {
        infoWindow.close();
      });
```
これで、やりたいことっぽくなった。

参考→https://www.doe.co.jp/hp-tips/api/google-maps-options/

> //監視できる要素の一例
	//map,marker,windowなど

**Comment by tanacchi** [comment]
あざます神
とりあえず解決したということで閉じるぜ
